version: '3.7'

services:

  depi1:
    container_name: depi1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - "REACT_APP_NODE_TYPE=PIZZA1"
      - "REACT_APP_CHANNEL=puzanova.ira2011@yandex.ru"
      - "REACT_APP_AUTHORIZATION=Basic S2Vra2VyVXNlcjp6RGZqbTMz"

  depi2:
    container_name: depi2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      - "REACT_APP_NODE_TYPE=PIZZA2"
      - "REACT_APP_CHANNEL=puzanova.ira2011@yandex.ru"
      - "REACT_APP_AUTHORIZATION=Basic S2Vra2VyVXNlcjp6RGZqbTMz"

  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    environment:
      - "REACT_APP_NODE_TYPE=DELIVERY"
      - "REACT_APP_CHANNEL=puzanova.ira2011@yandex.ru"
      - "REACT_APP_AUTHORIZATION=Basic S2Vra2VyVXNlcjp6RGZqbTMz"
